apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aiops-backend-monitor
  namespace: default
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: aiops-backend
  endpoints:
  - port: http
    interval: 10s
    path: /metrics