#!/usr/bin/env python3
"""
Healthy Data Collection — Phase 2 of the ML Training Pipeline
=========================================================

Reads `capacity_table.json` (generated by Phase 1) to know the safe
limits for each replica count. For each replica count it ramps traffic
continuously (+1 VU at a time) from the bottom of that count's healthy
band up to its safe maximum and back down, recording Prometheus metrics.

Why a continuous ramp and not a few fixed load steps (4 readings each, as
before): steps leave gaps between load levels that a one-class model
learns as "not healthy", and the up + down ramp gives two independent
passes over the same loads, which train_health_baseline.py uses to
estimate false alarms on readings the model hasn't seen.

Why the bands overlap (OVERLAP): N replicas are trained from 70% of the
(N-1) safe load, not from 100%. Scale-up of N-1 fires above its safe max,
scale-down of N only below 70% of it, so the system can't flap at the
handover (deadband).

The training script fits one One-Class SVM per replica count.
Takes about 55 minutes for 3 replica counts.

Output:
  • baseline_metrics_healthy.csv
"""

import json
import random
import csv
import subprocess
import threading
import time
from datetime import datetime
from pathlib import Path

import requests as http_client

# ─── Configuration ──────────────────────────────────────────────────────────

PROMETHEUS_URL = "http://prometheus.aiops"
APP_BASE_URL = "http://mwtback.aiops"
DEPLOYMENT = "aiops-backend-deployment"
NAMESPACE = "default"

LOGIN_URL = f"{APP_BASE_URL}/auth/login"
LOGIN_PAYLOAD = json.dumps({"email": "user1@example.com", "password": "password123"})
LOGIN_HEADERS = {"Content-Type": "application/json"}

OUTPUT_DIR = Path(__file__).resolve().parent
CAPACITY_JSON = OUTPUT_DIR / "capacity_table.json"
OUTPUT_CSV = OUTPUT_DIR / "baseline_metrics_healthy.csv"

# Timing config for data collection
SETTLE_S = 60           # After a replica change, so the 1m rate() window only sees the new pods
READING_INTERVAL_S = 15 # Seconds between samples
READINGS_PER_VU = 2     # Ramp speed: +1 VU every 30s, so every reading sits at a different load
OVERLAP = 0.7           # Band of N replicas starts at 70% of (N-1)'s safe VUs (anti-flapping deadband)
# 1 replica only: extra readings at very low traffic, where p95 is noisy
# (~60 requests per 1m window). Low traffic on 1 pod is always normal.
LOW_VU_MAX = 3
LOW_VU_READINGS = 6

# Prometheus queries
QUERIES = {
    "avg_cpu_per_pod": (
        'sum(rate(container_cpu_usage_seconds_total'
        '{namespace="default", pod=~"aiops-backend-deployment-.*",'
        ' container!=""}[1m]))'
        ' / scalar(kube_deployment_status_replicas_available'
        '{namespace="default",'
        ' deployment="aiops-backend-deployment"})'
    ),
    "throughput": (
        'sum(rate(http_requests_total{app="aiops-backend"}[1m]))'
    ),
    "latency_p95": (
        'histogram_quantile(0.95,'
        ' sum(rate(http_request_duration_seconds_bucket'
        '{app="aiops-backend"}[1m])) by (le))'
    ),
    "active_replicas": (
        'kube_deployment_status_replicas_available'
        '{namespace="default",'
        ' deployment="aiops-backend-deployment"}'
    ),
    "cpu_throttling": (
        'sum(increase(container_cpu_cfs_throttled_periods_total'
        '{namespace="default", pod=~"aiops-backend-deployment-.*",'
        ' container!=""}[1m]))'
        ' / sum(increase(container_cpu_cfs_periods_total'
        '{namespace="default", pod=~"aiops-backend-deployment-.*",'
        ' container!=""}[1m]))'
    ),
}

# ─── Traffic Generator ──────────────────────────────────────────────────────

def _user_loop(stop_event: threading.Event):
    """Simulate one user continuously hitting the /auth/login endpoint.
    Each user has its own stop_event, so one user can leave without
    interrupting the others."""
    # Random start offset so users don't fire in lockstep: k6 ramps VUs in
    # gradually, so live traffic arrives spread out rather than in bursts.
    if stop_event.wait(random.uniform(0, 1)):
        return
    session = http_client.Session()
    while not stop_event.is_set():
        try:
            session.post(
                LOGIN_URL,
                data=LOGIN_PAYLOAD,
                headers=LOGIN_HEADERS,
                timeout=10,
            )
        except Exception:
            pass
        # 1s sleep between requests for controlled throughput
        stop_event.wait(1)


class TrafficGenerator:
    """Manages a pool of virtual users (one stop event per user)."""
    def __init__(self):
        self._users: list[threading.Event] = []

    def set_users(self, target_count: int):
        """Add or remove users one at a time, so the ramp has no traffic gaps."""
        while len(self._users) < target_count:
            stop = threading.Event()
            threading.Thread(target=_user_loop, args=(stop,), daemon=True).start()
            self._users.append(stop)
        while len(self._users) > target_count:
            self._users.pop().set()

    @property
    def active_users(self) -> int:
        return len(self._users)

    def stop_all(self):
        self.set_users(0)


# ─── Kubernetes Helpers ─────────────────────────────────────────────────────

def scale_deployment(replicas: int):
    subprocess.run(
        [
            "kubectl", "scale", "deployment", DEPLOYMENT,
            f"--replicas={replicas}", "-n", NAMESPACE,
        ],
        check=True,
        capture_output=True,
    )


def wait_for_replicas(target: int, timeout: int = 120) -> bool:
    deadline = time.time() + timeout
    while time.time() < deadline:
        val = _fetch_one("active_replicas")
        if val is not None and int(val) == target:
            return True
        time.sleep(5)
    return False


# ─── Prometheus Helpers ─────────────────────────────────────────────────────

def _fetch_one(name: str):
    try:
        r = http_client.get(
            f"{PROMETHEUS_URL}/api/v1/query",
            params={"query": QUERIES[name]},
            timeout=5,
        )
        r.raise_for_status()
        results = r.json().get("data", {}).get("result", [])
        if results:
            val = float(results[0]["value"][1])
            import math
            return None if math.isnan(val) else val
        return None
    except Exception:
        return None


def fetch_all() -> dict | None:
    metrics = {}
    for name in QUERIES:
        val = _fetch_one(name)
        if val is None:
            return None
        metrics[name] = val
    return metrics


# ─── Main Collection Loop ───────────────────────────────────────────────────

def ramp_path(start_vus: int, safe_vus: int) -> list[int]:
    """+1 VU from start to the safe max, then -1 VU back down to start."""
    if safe_vus <= start_vus:
        return [safe_vus]
    up = list(range(start_vus, safe_vus + 1))
    return up + up[-2::-1]


def band_start(replicas: int, first_replicas: int, capacity_table: dict) -> int:
    """Lowest VUs of the healthy band for this replica count."""
    if replicas == first_replicas:
        return 1  # 1 VU (~0.9 rps) so the detector has healthy low-traffic data
    prev_key = str(replicas - 1)
    if prev_key not in capacity_table:
        return 2
    # max(1, ...) so a previous count that failed (safe VUs 0)
    # never produces zero-traffic "healthy" samples.
    return max(1, round(OVERLAP * capacity_table[prev_key]["max_safe_vus"]))


def collect_data():
    if not CAPACITY_JSON.exists():
        print(f"Error: {CAPACITY_JSON} not found. Please run capacity_discovery.py first.")
        return

    with open(CAPACITY_JSON, "r") as f:
        capacity_table = json.load(f)

    print("=" * 70)
    print("  HEALTHY DATA COLLECTION — Phase 2")
    print("=" * 70)

    # Rows are written as they are collected, so a crash mid-run keeps
    # everything measured so far (the old version only saved at the end).
    fieldnames = ["timestamp", "vus", "avg_cpu_per_pod", "throughput", "latency_p95", "active_replicas", "cpu_throttling"]
    csv_file = open(OUTPUT_CSV, "w", newline="")
    writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
    writer.writeheader()
    rows_written = 0
    traffic = TrafficGenerator()

    try:
        # Sort replica keys numerically
        replica_counts = sorted([int(k) for k in capacity_table.keys()])

        for replicas in replica_counts:
            safe_vus = capacity_table[str(replicas)]["max_safe_vus"]
            if safe_vus < 2:
                print(f"  ⚠️ Skipping {replicas} replicas (safe VUs too low: {safe_vus})")
                continue

            print(f"\n{'─' * 70}")
            print(f"  🟢 Collecting for {replicas} replica(s) [Max Safe VUs: {safe_vus}]")
            print(f"{'─' * 70}")

            scale_deployment(replicas)
            print(f"  Waiting for {replicas} pod(s) to be ready ...", end="", flush=True)
            if not wait_for_replicas(replicas):
                print(f" ⚠️ timeout! Skipping.")
                continue
            print(f" ready.")

            start_vus = band_start(replicas, replica_counts[0], capacity_table)
            path = ramp_path(start_vus, safe_vus)
            print(f"  Ramp: {start_vus} → {safe_vus} → {start_vus} VUs")

            traffic.set_users(start_vus)
            print(f"  Settling {SETTLE_S}s at {start_vus} VUs...", end="", flush=True)
            time.sleep(SETTLE_S)
            print(" done.")

            for vu_target in path:
                traffic.set_users(vu_target)
                low_traffic = replicas == replica_counts[0] and vu_target <= LOW_VU_MAX
                n_readings = LOW_VU_READINGS if low_traffic else READINGS_PER_VU
                print(f"  📊 {vu_target:3d} VUs ", end="", flush=True)
                for _ in range(n_readings):
                    time.sleep(READING_INTERVAL_S)
                    metrics = fetch_all()
                    if metrics is not None:
                        row = {
                            "timestamp": datetime.now().strftime("%H:%M:%S"),
                            "vus": vu_target,
                            **metrics
                        }
                        writer.writerow(row)
                        csv_file.flush()
                        rows_written += 1
                        print(".", end="", flush=True)
                    else:
                        print("x", end="", flush=True) # metric fetch failed
                print()

            traffic.stop_all()

    except KeyboardInterrupt:
        print("\n\n⏹️ Interrupted by user. Data collected so far is already saved.")
    finally:
        csv_file.close()
        traffic.stop_all()
        try:
            scale_deployment(1)
            print("\n  Reset deployment to 1 replica.")
        except Exception:
            pass

    if rows_written:
        print(f"\n✅ Successfully collected {rows_written} healthy data points!")
        print(f"📄 Saved to: {OUTPUT_CSV}")
        print("\n🚀 Next step: Run `python train_health_baseline.py` to train the scale-aware model.")
    else:
        print("\n⚠️ No data was collected.")


if __name__ == "__main__":
    collect_data()
