#!/usr/bin/env python3
"""
Healthy Data Collection — Phase 2 of the ML Training Pipeline
=========================================================

Reads `capacity_table.json` (generated by Phase 1) to know the safe 
limits for each replica count. Then, it iterates through each replica 
count, generating varying levels of "healthy" traffic (from very low 
up to the safe maximum), and continuously records Prometheus metrics.

The resulting dataset contains a diverse, balanced representation of 
healthy states across all scale levels, perfect for training a scale-aware
Isolation Forest.

Output:
  • baseline_metrics_healthy.csv
"""

import json
import csv
import subprocess
import threading
import time
from datetime import datetime
from pathlib import Path

import requests as http_client

# ─── Configuration ──────────────────────────────────────────────────────────

PROMETHEUS_URL = "http://prometheus.aiops"
APP_BASE_URL = "http://mwtback.aiops"
DEPLOYMENT = "aiops-backend-deployment"
NAMESPACE = "default"

LOGIN_URL = f"{APP_BASE_URL}/auth/login"
LOGIN_PAYLOAD = json.dumps({"email": "user1@example.com", "password": "password123"})
LOGIN_HEADERS = {"Content-Type": "application/json"}

OUTPUT_DIR = Path(__file__).resolve().parent
CAPACITY_JSON = OUTPUT_DIR / "capacity_table.json"
OUTPUT_CSV = OUTPUT_DIR / "baseline_metrics_healthy.csv"

# Timing config for data collection
SETTLE_S = 45           # Wait after changing traffic before measuring
READINGS_PER_STEP = 6   # How many samples to take at a specific VU level
READING_INTERVAL_S = 15 # Seconds between samples

# Prometheus queries
QUERIES = {
    "avg_cpu_per_pod": (
        'sum(rate(container_cpu_usage_seconds_total'
        '{namespace="default", pod=~"aiops-backend-deployment-.*",'
        ' container!=""}[1m]))'
        ' / scalar(kube_deployment_status_replicas_available'
        '{namespace="default",'
        ' deployment="aiops-backend-deployment"})'
    ),
    "throughput": (
        'sum(rate(http_requests_total{app="aiops-backend"}[1m]))'
    ),
    "latency_p95": (
        'histogram_quantile(0.95,'
        ' sum(rate(http_request_duration_seconds_bucket'
        '{app="aiops-backend"}[1m])) by (le))'
    ),
    "active_replicas": (
        'kube_deployment_status_replicas_available'
        '{namespace="default",'
        ' deployment="aiops-backend-deployment"}'
    ),
    "cpu_throttling": (
        'sum(increase(container_cpu_cfs_throttled_periods_total'
        '{namespace="default", pod=~"aiops-backend-deployment-.*",'
        ' container!=""}[1m]))'
        ' / sum(increase(container_cpu_cfs_periods_total'
        '{namespace="default", pod=~"aiops-backend-deployment-.*",'
        ' container!=""}[1m]))'
    ),
}

# ─── Traffic Generator ──────────────────────────────────────────────────────

def _user_loop(stop_event: threading.Event):
    """Simulate one user continuously hitting the /auth/login endpoint."""
    session = http_client.Session()
    while not stop_event.is_set():
        try:
            session.post(
                LOGIN_URL,
                data=LOGIN_PAYLOAD,
                headers=LOGIN_HEADERS,
                timeout=10,
            )
        except Exception:
            pass
        # 1s sleep between requests for controlled throughput
        time.sleep(1)


class TrafficGenerator:
    """Manages a pool of virtual users."""
    def __init__(self):
        self._threads: list[threading.Thread] = []
        self._stop = threading.Event()

    def set_users(self, target_count: int):
        """Scale the number of active virtual users up or down to target_count."""
        current = len(self._threads)
        if target_count > current:
            for _ in range(target_count - current):
                t = threading.Thread(target=_user_loop, args=(self._stop,), daemon=True)
                t.start()
                self._threads.append(t)
        elif target_count < current:
            # To scale down, we stop everything and restart the target amount.
            # (Simpler than signaling specific threads to stop)
            self.stop_all()
            for _ in range(target_count):
                t = threading.Thread(target=_user_loop, args=(self._stop,), daemon=True)
                t.start()
                self._threads.append(t)

    @property
    def active_users(self) -> int:
        return len(self._threads)

    def stop_all(self):
        """Signal all threads to stop and wait briefly."""
        self._stop.set()
        time.sleep(1.5)
        self._threads.clear()
        self._stop = threading.Event()


# ─── Kubernetes Helpers ─────────────────────────────────────────────────────

def scale_deployment(replicas: int):
    subprocess.run(
        [
            "kubectl", "scale", "deployment", DEPLOYMENT,
            f"--replicas={replicas}", "-n", NAMESPACE,
        ],
        check=True,
        capture_output=True,
    )


def wait_for_replicas(target: int, timeout: int = 120) -> bool:
    deadline = time.time() + timeout
    while time.time() < deadline:
        val = _fetch_one("active_replicas")
        if val is not None and int(val) == target:
            return True
        time.sleep(5)
    return False


# ─── Prometheus Helpers ─────────────────────────────────────────────────────

def _fetch_one(name: str):
    try:
        r = http_client.get(
            f"{PROMETHEUS_URL}/api/v1/query",
            params={"query": QUERIES[name]},
            timeout=5,
        )
        r.raise_for_status()
        results = r.json().get("data", {}).get("result", [])
        if results:
            val = float(results[0]["value"][1])
            import math
            return None if math.isnan(val) else val
        return None
    except Exception:
        return None


def fetch_all() -> dict | None:
    metrics = {}
    for name in QUERIES:
        val = _fetch_one(name)
        if val is None:
            return None
        metrics[name] = val
    return metrics


# ─── Main Collection Loop ───────────────────────────────────────────────────

def collect_data():
    if not CAPACITY_JSON.exists():
        print(f"Error: {CAPACITY_JSON} not found. Please run capacity_discovery.py first.")
        return

    with open(CAPACITY_JSON, "r") as f:
        capacity_table = json.load(f)

    print("=" * 70)
    print("  HEALTHY DATA COLLECTION — Phase 2")
    print("=" * 70)

    dataset = []
    traffic = TrafficGenerator()

    try:
        # Sort replica keys numerically
        replica_counts = sorted([int(k) for k in capacity_table.keys()])

        for replicas in replica_counts:
            safe_vus = capacity_table[str(replicas)]["max_safe_vus"]
            if safe_vus < 2:
                print(f"  ⚠️ Skipping {replicas} replicas (safe VUs too low: {safe_vus})")
                continue

            print(f"\n{'─' * 70}")
            print(f"  🟢 Collecting for {replicas} replica(s) [Max Safe VUs: {safe_vus}]")
            print(f"{'─' * 70}")

            scale_deployment(replicas)
            print(f"  Waiting for {replicas} pod(s) to be ready ...", end="", flush=True)
            if not wait_for_replicas(replicas):
                print(f" ⚠️ timeout! Skipping.")
                continue
            print(f" ready.")
            print("  Settling pods for 45s...")
            time.sleep(45)

            # Start traffic from previous replica's safe max.
            # This teaches the model that each replica count has its own
            # expected traffic range — low traffic + many pods = waste.
            prev_key = str(replicas - 1)
            if replicas == replica_counts[0]:
                start_vus = 2  # First replica level starts from scratch
            elif prev_key in capacity_table:
                start_vus = capacity_table[prev_key]["max_safe_vus"]
            else:
                start_vus = 2

            # Create 4 evenly-spaced load steps from start to safe max
            span = safe_vus - start_vus
            if span <= 0:
                steps = [safe_vus]
            else:
                steps = [
                    start_vus,
                    start_vus + span // 3,
                    start_vus + 2 * span // 3,
                    safe_vus,
                ]
            # Remove duplicates and sort
            steps = sorted(list(set(steps)))

            for vu_target in steps:
                traffic.set_users(vu_target)
                print(f"\n  📊 Target: {vu_target} VUs │ settling {SETTLE_S}s...", end="", flush=True)
                time.sleep(SETTLE_S)
                print(" done.")

                print(f"  Scraping metrics ({READINGS_PER_STEP} readings) ", end="", flush=True)
                for _ in range(READINGS_PER_STEP):
                    metrics = fetch_all()
                    if metrics is not None:
                        row = {
                            "timestamp": datetime.now().strftime("%H:%M:%S"),
                            **metrics
                        }
                        dataset.append(row)
                        print(".", end="", flush=True)
                    else:
                        print("x", end="", flush=True) # metric fetch failed
                    time.sleep(READING_INTERVAL_S)
                print(" done.")

            traffic.stop_all()

    except KeyboardInterrupt:
        print("\n\n⏹️ Interrupted by user. Saving collected data...")
    finally:
        traffic.stop_all()
        try:
            scale_deployment(1)
            print("\n  Reset deployment to 1 replica.")
        except Exception:
            pass

    # ─── Save results ────────────────────────────────────────────────────
    if dataset:
        fieldnames = ["timestamp", "avg_cpu_per_pod", "throughput", "latency_p95", "active_replicas", "cpu_throttling"]
        with open(OUTPUT_CSV, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(dataset)
        
        print(f"\n✅ Successfully collected {len(dataset)} healthy data points!")
        print(f"📄 Saved to: {OUTPUT_CSV}")
        print("\n🚀 Next step: Run `python train_health_baseline.py` to train the scale-aware model.")
    else:
        print("\n⚠️ No data was collected.")


if __name__ == "__main__":
    collect_data()
